# SPDX-License-Identifier: Apache-2.0
"""Meridian V1 deterministic synthetic-data generation plugin."""

from ._version import __version__
from .errors import (
    CancelledRun,
    ExceededBudget,
    InvalidSpec,
    NondeterministicImplementation,
    PublicationFailure,
    SinkConflict,
    SourcePolicyViolation,
    SyntheticError,
    SyntheticErrorCode,
    UnknownGenerator,
    ValidationFailure,
)
from .evidence import CollectingEvidenceHook, EvidenceHook, MeridianEvidenceHook, RunEvidence
from .execution import (
    IMPLEMENTATION_COORDINATE,
    CancellationToken,
    Generator,
    MeridianSourceReader,
    RunProgress,
    RunState,
    SourceReader,
    SourceTransformation,
    SourceTransformationRegistry,
    SyntheticRun,
)
from .generators import (
    GenerationContext,
    GeneratorDefinition,
    GeneratorRegistry,
    builtin_registry,
    default_generator_id,
)
from .plugin import Synthetic, SyntheticPluginFactory, plugin_manifest
from .publication import (
    ArtifactPublication,
    ArtifactPublisher,
    DatasetManifest,
    InMemoryArtifactPublisher,
)
from .repository import SyntheticRepository, SyntheticResources
from .schema import SyntheticSchemaProvider
from .sinks import (
    CanonicalDatasetSink,
    DirectWritePolicy,
    InMemoryCheckpointStore,
    InMemoryPartitionStore,
    MemorySink,
    MeridianRecordSink,
    MeridianStreamingSink,
    PartitionReceipt,
    RecordPartition,
    RecordSink,
    SinkKind,
    TargetClass,
)
from .spec import (
    CollectionSpec,
    CorrelationSpec,
    ExecutionBounds,
    FieldGeneratorSpec,
    ImplementationPin,
    OutputMode,
    RelationSpec,
    SourceSpec,
    SyntheticSpec,
    SyntheticSpecV1,
    TimeBounds,
    ValidationRuleSpec,
)
from .validation import RuleResult, ValidationReport, ValidationStatus

__all__ = [
    "IMPLEMENTATION_COORDINATE",
    "ArtifactPublication",
    "ArtifactPublisher",
    "CancellationToken",
    "CancelledRun",
    "CanonicalDatasetSink",
    "CollectingEvidenceHook",
    "CollectionSpec",
    "CorrelationSpec",
    "DatasetManifest",
    "DirectWritePolicy",
    "EvidenceHook",
    "ExceededBudget",
    "ExecutionBounds",
    "FieldGeneratorSpec",
    "GenerationContext",
    "Generator",
    "GeneratorDefinition",
    "GeneratorRegistry",
    "ImplementationPin",
    "InMemoryArtifactPublisher",
    "InMemoryCheckpointStore",
    "InMemoryPartitionStore",
    "InvalidSpec",
    "MemorySink",
    "MeridianEvidenceHook",
    "MeridianRecordSink",
    "MeridianSourceReader",
    "MeridianStreamingSink",
    "NondeterministicImplementation",
    "OutputMode",
    "PartitionReceipt",
    "PublicationFailure",
    "RecordPartition",
    "RecordSink",
    "RelationSpec",
    "RuleResult",
    "RunEvidence",
    "RunProgress",
    "RunState",
    "SinkConflict",
    "SinkKind",
    "SourcePolicyViolation",
    "SourceReader",
    "SourceSpec",
    "SourceTransformation",
    "SourceTransformationRegistry",
    "Synthetic",
    "SyntheticError",
    "SyntheticErrorCode",
    "SyntheticPluginFactory",
    "SyntheticRepository",
    "SyntheticResources",
    "SyntheticRun",
    "SyntheticSchemaProvider",
    "SyntheticSpec",
    "SyntheticSpecV1",
    "TargetClass",
    "TimeBounds",
    "UnknownGenerator",
    "ValidationFailure",
    "ValidationReport",
    "ValidationRuleSpec",
    "ValidationStatus",
    "__version__",
    "builtin_registry",
    "default_generator_id",
    "plugin_manifest",
]
